#This compose file adds draw.io to your stack
version: '3.5'
services:
  drawio:
    image: mondrian/diagrams:22.1.15_mondrian_2.5.5
    build: 
      context: ./main
      args:
        APP_BUILD: none
        APP_VERSION: v22.1.15+mondrian_2.5.5
    container_name: mondrian-diagrams
    restart: unless-stopped
    ports:
      - 80:8080
      - 443:8443
    environment:
      SSL_HOST_DEFAULT: dev.mondrian-it.io
      SSL_HOSTS: "diagrams-dev.mondrian-it.io,diagrams-dev.mondrian-it.io"
      #DRAWIO_CSP_HEADER: default-src \'self\'; script-src \'self\' https://storage.googleapis.com https://apis.google.com https://docs.google.com https://code.jquery.com \'unsafe-inline\'; connect-src \'self\' https://*.mondrian-it.io https://*.dropboxapi.com https://api.trello.com https://api.github.com https://raw.githubusercontent.com https://*.googleapis.com https://*.googleusercontent.com https://graph.microsoft.com https://*.1drv.com https://*.sharepoint.com https://gitlab.com https://*.google.com https://fonts.gstatic.com https://fonts.googleapis.com; img-src * data:; media-src * data:; font-src * about:; style-src \'self\' \'unsafe-inline\' https://fonts.googleapis.com; frame-src \'self\' https://*.google.com;
      MONDRIAN_ROOT: mondrian/
      MONDRIAN_CONFIGURATION_PATH: diagrams_config/
      MONDRIAN_CONFIGURATION_FILE: mondrianDiagrams.configuration
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./.keystore:/usr/local/tomcat/.keystore
      - ../mondrianCertificates:/usr/local/tomcat/certificates
      - ../mondrianConfig:/usr/local/tomcat/webapps/draw/mondrian