#This compose file adds draw.io to your stack
version: '3.5'
services:
  drawio:
    image: mondrian/diagrams:22.1.15_mondrian_2.5.6
    build: 
      context: ./main
      args:
        APP_BUILD: none
        APP_VERSION: v22.1.15+mondrian_2.5.6
    container_name: mondrian-diagrams
    restart: unless-stopped
    ports:
      - 80:8080
      - 443:8443
    environment:
      SSL_HOST_DEFAULT: dev.mondrian-it.io
      SSL_HOSTS: "dev.mondrian-it.io,diagrams-dev.mondrian-it.io"
      MONDRIAN_ROOT: mondrian/
      MONDRIAN_CONFIGURATION_PATH: diagrams_config/
      MONDRIAN_CONFIGURATION_FILE: mondrianDiagrams.configuration
    env_file:
      - github.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ../mondrianCertificates:/usr/local/tomcat/certificates
      - ../mondrianConfig:/usr/local/tomcat/webapps/draw/mondrian