#This compose file adds Mondrian Diagrams to your stack
version: '3.5'
services:
  mondrian-diagrams:
    image: mondrian/diagrams:22.1.16_mondrian_2.5.9
    build: 
      context: ./main
      args:
        APP_BUILD: none
        APP_VERSION: v22.1.16+mondrian_2.5.9
    container_name: mondrian-diagrams
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    labels:
      - "traefik.enable=true"
    # ROUTERS
      - "traefik.http.routers.mondrian-diagrams.rule=Host(`diagrams.mondrian-it.io`)"
      - "traefik.http.routers.mondrian-diagrams.tls=true"
      - "traefik.http.routers.mondrian-diagrams.entrypoints=web-secure"
      - "traefik.http.routers.mondrian-diagrams.middlewares=default@file"

    networks:
      - proxy_network
    restart: unless-stopped
    environment:
      SSL_HOST_DEFAULT: diagrams.mondrian-it.io
      SSL_HOSTS: "diagrams.mondrian-it.io"
      MONDRIAN_ROOT: mondrian
      MONDRIAN_CONFIGURATION_PATH: /
      MONDRIAN_CONFIGURATION_FILE: mondrianDiagrams.configuration
    env_file:
      - github.env
    extra_hosts:
      github.com: "140.82.121.4"
    volumes:
      - /etc/letsencrypt:/usr/local/tomcat/certificates:ro
      - ../mondrianConfig/diagrams.mondrian-it.io/diagrams_config:/usr/local/tomcat/webapps/draw/mondrian:ro

  mondrian-diagrams-dev:
    image: mondrian/diagrams:22.1.18_mondrian_2.5.9
    build: 
      context: ./main
      args:
        APP_BUILD: none
        APP_VERSION: v22.1.18+mondrian_2.5.9
    container_name: mondrian-diagrams-dev
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    labels:
      - "traefik.enable=true"
    # ROUTERS
      - "traefik.http.routers.mondrian-diagrams-dev.rule=Host(`diagrams-dev.mondrian-it.io`)"
      - "traefik.http.routers.mondrian-diagrams-dev.tls=true"
      - "traefik.http.routers.mondrian-diagrams-dev.entrypoints=web-secure"
      - "traefik.http.routers.mondrian-diagrams-dev.middlewares=secured@file"
      
    networks:
      - proxy_network
    restart: unless-stopped
    environment:
      SSL_HOST_DEFAULT: diagrams-dev.mondrian-it.io
      SSL_HOSTS: "diagrams-dev.mondrian-it.io,dev.mondrian-it.io"
      MONDRIAN_ROOT: mondrian
      MONDRIAN_CONFIGURATION_PATH: /
      MONDRIAN_CONFIGURATION_FILE: mondrianDiagrams.configuration
    env_file:
      - github.env
    extra_hosts:
      github.com: "140.82.121.4"
    volumes:
      - /etc/letsencrypt:/usr/local/tomcat/certificates:ro
      - ../mondrianConfig/diagrams-dev.mondrian-it.io/diagrams_config:/usr/local/tomcat/webapps/draw/mondrian:ro
      - ../mondrianConfig/extraFiles/cacerts-modified:/opt/java/openjdk/lib/security/cacerts:ro

  mondrian-athena-diagrams:
      image: mondrian/diagrams:22.1.16_mondrian_2.5.9
      build: 
        context: ./main
        args:
          APP_BUILD: none
          APP_VERSION: v22.1.16+mondrian_2.5.9
      container_name: mondrian-athena-diagrams
      deploy:
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 128M
      labels:
        - "traefik.enable=true"
      # ROUTERS
        - "traefik.http.routers.mondrian-athena-diagrams.rule=Host(`athena-diagrams.mondrian-it.io`)"
        - "traefik.http.routers.mondrian-athena-diagrams.tls=true"
        - "traefik.http.routers.mondrian-athena-diagrams.entrypoints=web-secure"
        - "traefik.http.routers.mondrian-athena-diagrams.middlewares=secured@file"

      networks:
        - proxy_network
      restart: unless-stopped
      environment:
        SSL_HOST_DEFAULT: athena-diagrams.mondrian-it.io
        SSL_HOSTS: "athena-diagrams.mondrian-it.io"
        MONDRIAN_ROOT: mondrian
        MONDRIAN_CONFIGURATION_PATH: /
        MONDRIAN_CONFIGURATION_FILE: mondrianDiagrams.configuration
      env_file:
        - github.env
      extra_hosts:
        github.com: "140.82.121.4"
      volumes:
        - /etc/letsencrypt:/usr/local/tomcat/certificates:ro
        - ../mondrianConfig/athena-diagrams.mondrian-it.io/diagrams_config:/usr/local/tomcat/webapps/draw/mondrian:ro

networks:
  proxy_network:
    name: proxy_network
    external: true