#This compose file adds draw.io to your stack
version: '3.5'
services:
  drawio:
    image: mondrian/diagrams:22.1.15_mondrian_2.5.0
    build: 
      context: ./main
      args:
        APP_BUILD: none
        APP_VERSION: v22.1.15+mondrian_2.5.0
    container_name: mondrian-diagrams
    restart: unless-stopped
    ports:
      - 80:8080
      - 443:8443
    environment:
      PUBLIC_DNS: dev.mondrian-it.io
      SSL_HOSTS: "dev2.mondrian-it.io,dev3.mondrian-it.io"
      DRAWIO_SERVER_URL: https://dev.mondrian-it.io/
      DRAWIO_VIEWER_URL: https://dev.mondrian-it.io/js/viewer.min.js
      DRAWIO_LIGHTBOX_URL: https://dev.mondrian-it.io/
      DRAWIO_CSP_HEADER: default-src \'self\'; script-src \'self\' https://storage.googleapis.com https://apis.google.com https://docs.google.com https://code.jquery.com \'unsafe-inline\'; connect-src \'self\' https://dev.mondrian-it.io https://*.dropboxapi.com https://api.trello.com https://api.github.com https://raw.githubusercontent.com https://*.googleapis.com https://*.googleusercontent.com https://graph.microsoft.com https://*.1drv.com https://*.sharepoint.com https://gitlab.com https://*.google.com https://fonts.gstatic.com https://fonts.googleapis.com; img-src * data:; media-src * data:; font-src * about:; style-src \'self\' \'unsafe-inline\' https://fonts.googleapis.com; frame-src \'self\' https://*.google.com;
      MONDRIAN_CONFIGURATION: mondrian/mondrianDiagrams.configuration
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./.keystore:/usr/local/tomcat/.keystore
      - /etc/letsencrypt/live:/usr/local/tomcat/certificates
      - ../mondrianConfig/diagrams_config:/usr/local/tomcat/webapps/draw/mondrian